export const data = [
  {
    "id": 1,
    "name": "aptonoth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 2,
    "name": "larinoth",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 3,
    "name": "velociprey",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 4,
    "name": "velocidrome",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 5,
    "name": "kulu-ya-ku",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "hold rock",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 6,
    "name": "bnahabra (blue)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 7,
    "name": "konchu (yellow)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 8,
    "name": "yian kut-ku",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 9,
    "name": "bullfango",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 10,
    "name": "bulldrome",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 11,
    "name": "pukei-pukei",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 12,
    "name": "apceros",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 13,
    "name": "slagtoth (green)",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 14,
    "name": "gargwa",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 15,
    "name": "jaggi",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 16,
    "name": "jaggia",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 17,
    "name": "great jaggi",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 18,
    "name": "ludroth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 19,
    "name": "royal ludroth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 20,
    "name": "tetsucabra",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 21,
    "name": "arzuros",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 22,
    "name": "qurupeco",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 23,
    "name": "blue yian kut-ku",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 24,
    "name": "tigrex",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 25,
    "name": "monoblos",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 26,
    "name": "paolumu",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "balloon mode",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 27,
    "name": "basarios",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 28,
    "name": "yian garuga",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 29,
    "name": "duramboros",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 30,
    "name": "nargacuga",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 31,
    "name": "rathian",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "dragon"
  },
  {
    "id": 32,
    "name": "popo",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 33,
    "name": "konchu (blue)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 34,
    "name": "bnahabra (green)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 35,
    "name": "conga",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 36,
    "name": "congalala",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 37,
    "name": "baggi",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 38,
    "name": "great baggi",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 39,
    "name": "kecha wacha",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 40,
    "name": "gypceros",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 41,
    "name": "zamite",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 42,
    "name": "zamtrios",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "ice mode",
    "attackThree": "power",
    "attackThreeCondition": "inflated",
    "elementalWeakness": "thunder"
  },
  {
    "id": 43,
    "name": "nerscylla",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 44,
    "name": "barroth",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "covered in mud",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 45,
    "name": "tobi-kadachi",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "power",
    "attackThreeCondition": "overcharge",
    "elementalWeakness": "water"
  },
  {
    "id": 46,
    "name": "khezu",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 47,
    "name": "red khezu",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "speed",
    "attackThreeCondition": "charged",
    "elementalWeakness": "iwater"
  },
  {
    "id": 48,
    "name": "seltas",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 49,
    "name": "seltas queen",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "power",
    "attackThreeCondition": "combined",
    "elementalWeakness": "fire"
  },
  {
    "id": 50,
    "name": "lagombi",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 51,
    "name": "jade barroth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "tech",
    "attackThreeCondition": "covered in snow",
    "elementalWeakness": "thunder"
  },
  {
    "id": 52,
    "name": "anjanath",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 53,
    "name": "gammoth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "snow slurped",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 54,
    "name": "zinogre",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "charged",
    "attackThree": "power",
    "attackThreeCondition": "super charged",
    "elementalWeakness": "ice"
  },
  {
    "id": 55,
    "name": "barioth",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 56,
    "name": "legiana",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "tech",
    "attackThreeCondition": "flying",
    "elementalWeakness": "thunder"
  },
  {
    "id": 57,
    "name": "slagtoth (brown)",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 58,
    "name": "banahabra (brown)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 59,
    "name": "konchu (red)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 60,
    "name": "cephalos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 61,
    "name": "hermitaur",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 62,
    "name": "uroktor",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 63,
    "name": "ioprey",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 64,
    "name": "iodrome",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 65,
    "name": "genprey",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 66,
    "name": "gendrome",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 67,
    "name": "plesioth",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 68,
    "name": "cephadrome",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 69,
    "name": "ash kecha wacha",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 70,
    "name": "purple gypceros",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 71,
    "name": "green nargacuga",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 72,
    "name": "diablos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 73,
    "name": "black diablos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 74,
    "name": "white monoblos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 75,
    "name": "crimson qurupeco",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 76,
    "name": "mizutsune",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 77,
    "name": "lagiacrus",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "tech",
    "attackThreeCondition": "electrified",
    "elementalWeakness": "fire"
  },
  {
    "id": 78,
    "name": "nargacuga",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 79,
    "name": "daimyo hermitaur",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 80,
    "name": "plum daimyo hermitaur",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 81,
    "name": "brute tigrex",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 82,
    "name": "purple ludroth",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 83,
    "name": "ruby basarios",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 84,
    "name": "gravios",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 85,
    "name": "altaroth",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 86,
    "name": "great thunderbug",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 87,
    "name": "konchu (green)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 88,
    "name": "shakalaka",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 89,
    "name": "desert seltas queen",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 90,
    "name": "green plesioth",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 91,
    "name": "shrouded nerscylla",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 92,
    "name": "emerald congalala",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 93,
    "name": "agnaktor",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "power",
    "attackThreeCondition": "lava mode",
    "elementalWeakness": "water"
  },
  {
    "id": 94,
    "name": "black gravios",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 95,
    "name": "ivory lagiacrus",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "tech",
    "attackThreeCondition": "electrified",
    "elementalWeakness": "dragon"
  },
  {
    "id": 96,
    "name": "brachydios",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enrage",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 97,
    "name": "nergigante",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "spike armor",
    "attackThree": "speed",
    "attackThreeCondition": "enraged",
    "elementalWeakness": "thunder"
  },
  {
    "id": 98,
    "name": "astalos",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "electrified",
    "attackThree": "speed",
    "attackThreeCondition": "flying",
    "elementalWeakness": "ice"
  },
  {
    "id": 99,
    "name": "glavenus",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "fireball charge",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 100,
    "name": "glacial agnaktor",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "power",
    "attackThreeCondition": "snow mode",
    "elementalWeakness": "fire"
  },
  {
    "id": 101,
    "name": "bazelgeuse",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 102,
    "name": "remobra",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 103,
    "name": "great dracophage bug",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 104,
    "name": "banahabra (red)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 105,
    "name": "vespoid",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 106,
    "name": "sand barioth",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 107,
    "name": "deviljho",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "dragon"
  },
  {
    "id": 108,
    "name": "stygian zinogre",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 109,
    "name": "seregios",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 110,
    "name": "barrel felyne",
    "attackOne": "",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": ""
  },
  {
    "id": 111,
    "name": "rathalos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged, note can be tech",
    "attackThree": "speed",
    "attackThreeCondition": "flying",
    "elementalWeakness": "thunder"
  },
  {
    "id": 112,
    "name": "azure rathalos",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "speed",
    "attackThreeCondition": "flying",
    "elementalWeakness": "dragon"
  },
  {
    "id": 113,
    "name": "pink rathian",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "dragon"
  },
  {
    "id": 114,
    "name": "fulgur anjanath",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "",
    "attackTwoCondition": "",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 115,
    "name": "silverwind nargacuga",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 116,
    "name": "thunderlord zinogre",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "charged and thunderbugs",
    "attackThree": "tech",
    "attackThreeCondition": "full charge",
    "elementalWeakness": "ice"
  },
  {
    "id": 117,
    "name": "bloodbath diablos",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged or heavy weight",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  },
  {
    "id": 118,
    "name": "grimclaw tigrex",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 119,
    "name": "dreadqueen rathian",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "dragon"
  },
  {
    "id": 120,
    "name": "kirin",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "fire"
  },
  {
    "id": 121,
    "name": "teostra",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "tech",
    "attackThreeCondition": "flying",
    "elementalWeakness": "water"
  },
  {
    "id": 122,
    "name": "rajang",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "charged",
    "attackThree": "tech",
    "attackThreeCondition": "depends on buff can also be speed!",
    "elementalWeakness": "ice"
  },
  {
    "id": 123,
    "name": "kushala daora",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "speed",
    "attackThreeCondition": "flying",
    "elementalWeakness": "thunder"
  },
  {
    "id": 124,
    "name": "velkhana",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "tech",
    "attackTwoCondition": "covered in ice",
    "attackThree": "power",
    "attackThreeCondition": "flying",
    "elementalWeakness": "fire"
  },
  {
    "id": 125,
    "name": "Kulve Taroth (Armored)",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "thunder"
  },
  {
    "id": 126,
    "name": "Kulve Taroth (No Armor)",
    "attackOne": "speed",
    "attackOneCondition": "normal",
    "attackTwo": "power",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 127,
    "name": "Boltreaver Astalos",
    "attackOne": "tech",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "after it lands",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "ice"
  },
  {
    "id": 128,
    "name": "Hellblade Glavenus",
    "attackOne": "power",
    "attackOneCondition": "normal",
    "attackTwo": "speed",
    "attackTwoCondition": "enraged",
    "attackThree": "",
    "attackThreeCondition": "",
    "elementalWeakness": "water"
  }
]
